In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences 
sent = ['the glass of milk ',
        'the cup of tea',
        'the glass of juice',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']


sent


['the glass of milk ',
 'the cup of tea',
 'the glass of juice',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
# Define the vocabulary size 
voc_size = 10000

In [8]:
### One Hot Representation 
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[1145, 6911, 265, 4703],
 [1145, 7249, 265, 9033],
 [1145, 6911, 265, 608],
 [9263, 1850, 3840, 5072, 571],
 [9263, 1850, 3840, 5072, 9096],
 [5718, 1145, 6825, 265, 4240],
 [5663, 3038, 1281, 5072]]

In [10]:
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np



In [13]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 1145, 6911,  265, 4703],
       [   0,    0,    0,    0, 1145, 7249,  265, 9033],
       [   0,    0,    0,    0, 1145, 6911,  265,  608],
       [   0,    0,    0, 9263, 1850, 3840, 5072,  571],
       [   0,    0,    0, 9263, 1850, 3840, 5072, 9096],
       [   0,    0,    0, 5718, 1145, 6825,  265, 4240],
       [   0,    0,    0,    0, 5663, 3038, 1281, 5072]])

In [14]:
## feature representation

dim=10

In [16]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 192ms/step


array([[[ 0.00917312,  0.01683522, -0.01073388,  0.02455406,
         -0.01633368, -0.00356676,  0.02899742, -0.02853649,
         -0.03527944,  0.00593144],
        [ 0.00917312,  0.01683522, -0.01073388,  0.02455406,
         -0.01633368, -0.00356676,  0.02899742, -0.02853649,
         -0.03527944,  0.00593144],
        [ 0.00917312,  0.01683522, -0.01073388,  0.02455406,
         -0.01633368, -0.00356676,  0.02899742, -0.02853649,
         -0.03527944,  0.00593144],
        [ 0.00917312,  0.01683522, -0.01073388,  0.02455406,
         -0.01633368, -0.00356676,  0.02899742, -0.02853649,
         -0.03527944,  0.00593144],
        [ 0.04386014,  0.03670777,  0.03474465, -0.04045682,
          0.03649484,  0.01565104,  0.04891565,  0.00640613,
         -0.00208332, -0.04390154],
        [-0.0356944 ,  0.00964638, -0.03297728,  0.0387678 ,
         -0.03087106, -0.03221922, -0.03969426,  0.04184473,
         -0.04490315,  0.03064001],
        [-0.01930122,  0.0045522 , -0.0425704 ,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 1145, 6911,  265, 4703])